=== latacita/tallercan/trunk/es.unican.psanchez.teaching.sportTeamsManagement.persistenceLayer.xml/resources/SportTeamMng.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://personales.unican.es/sanchezbp/SportTeamMng" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:stm="http://personales.unican.es/sanchezbp/SportTeamMng">

    <xs:complexType name="Sport">
    	<xs:sequence>
    		<xs:element name="name" minOccurs="1" maxOccurs="1">
    			<xs:simpleType>
    				<xs:restriction base="xs:string">
    					<xs:minLength value="1"></xs:minLength>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="pointsPerWin" minOccurs="1"
    			maxOccurs="1">
    			<xs:simpleType>
    				<xs:restriction base="xs:int">
    					<xs:minInclusive value="1"></xs:minInclusive>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="pointsPerTie" minOccurs="1"
    			maxOccurs="1">
    			<xs:simpleType>
    				<xs:restriction base="xs:int">
    					<xs:minInclusive value="0"></xs:minInclusive>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="pointsPerDefeat" minOccurs="1"
    			maxOccurs="1">
    			<xs:simpleType>
    				<xs:restriction base="xs:int">
    					<xs:minInclusive value="0"></xs:minInclusive>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="teams" type="stm:Team" minOccurs="0" maxOccurs="1"></xs:element>
    	</xs:sequence>
    	
    </xs:complexType>

    <xs:complexType name="Team">
    	<xs:sequence>
    		<xs:element name="name" minOccurs="1" maxOccurs="1">
    			<xs:simpleType>
    				<xs:restriction base="xs:string">
    					<xs:minLength value="1"></xs:minLength>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="matchesPlayed" minOccurs="1"
    			maxOccurs="1">
    			<xs:simpleType>
    				<xs:restriction base="xs:int">
    					<xs:minInclusive value="0"></xs:minInclusive>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="matchesWon" minOccurs="1" maxOccurs="1">
    			<xs:simpleType>
    				<xs:restriction base="xs:int">
    					<xs:minInclusive value="0"></xs:minInclusive>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    		<xs:element name="matchesTied" minOccurs="1"
    			maxOccurs="1">
    			<xs:simpleType>
    				<xs:restriction base="xs:int">
    					<xs:minInclusive value="0"></xs:minInclusive>
    				</xs:restriction>
    			</xs:simpleType>
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>


    <xs:complexType name="SportList">
    	<xs:sequence>
    		<xs:element name="sport" type="stm:Sport" minOccurs="0" maxOccurs="unbounded"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:element name="Leagues" type="stm:SportList"></xs:element>
</xs:schema>

=== latacita/tallercan/trunk/es.unican.psanchez.teaching.sportTeamsManagement.persistenceLayer.xml.tests/SportTeamsMngData.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><stm:Leagues xmlns:stm="http://personales.unican.es/sanchezbp/SportTeamMng" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://personales.unican.es/sanchezbp/SportTeamMng ../../../../../../../../resources/SportTeamMng.xsd ">
	<stm:sport>
		<stm:name>Futbol</stm:name>
		<stm:pointsPerWin>3</stm:pointsPerWin>
		<stm:pointsPerTie>1</stm:pointsPerTie>
		<stm:pointsPerDefeat>0</stm:pointsPerDefeat>
	</stm:sport>
	<stm:sport>
		<stm:name>Baloncesto</stm:name>
		<stm:pointsPerWin>2</stm:pointsPerWin>
		<stm:pointsPerTie>0</stm:pointsPerTie>
		<stm:pointsPerDefeat>0</stm:pointsPerDefeat>
	</stm:sport>
	
</stm:Leagues>

=== latacita/tallercan/trunk/es.unican.psanchez.teaching.sportTeamsManagement.persistenceLayer.xml/src/es/unican/psanchez/teaching/sportTeamsManagement/persistenceLayer/xml/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<stm:Leagues xmlns:stm="http://personales.unican.es/sanchezbp/SportTeamMng" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://personales.unican.es/sanchezbp/SportTeamMng SportTeamMng.xsd ">
	<stm:sport>
		<stm:name>Futbol</stm:name>
		<stm:pointsPerWin>3</stm:pointsPerWin>
		<stm:pointsPerTie>1</stm:pointsPerTie>
		<stm:pointsPerDefeat>0</stm:pointsPerDefeat>
	</stm:sport>
	<stm:sport>
		<stm:name>Bolos</stm:name>
		<stm:pointsPerWin>1</stm:pointsPerWin>
		<stm:pointsPerTie>0</stm:pointsPerTie>
		<stm:pointsPerDefeat>0</stm:pointsPerDefeat>
	</stm:sport>
</stm:Leagues>
